export const ActionTypes = {
  FETCH_ANIME: "FETCH_ANIME",
  SET_ANIME: "SET_ANIME",
  SELECTED_ANIME: "SELECTED_ANIME",
  REMOVE_SELECTED_ANIME: "REMOVE_SELECTED_ANIME",
  ANIME_NAME: "ANIME_NAME",
  ANIME_DETAIL_NAME: "ANIME_DETAIL_NAME",
  ID_ANIME: "ID_ANIME",
};
